# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    
    command: --default-authentication-plugin=mysql_native_password
    # command: bash -c "mysql --user=root --password=123"
    # command: bash -c "ALTER USER root IDENTIFIED WITH mysql_native_password BY '123';"

    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      # - MYSQL_PASSWORD=123
      # - MYSQL_USER=root
      - MYSQL_DATABASE=testDb
    expose:
      - "3306"
    networks:
      appnet:
        ipv4_address: 172.25.0.100

  nodeapp:
    # build: ./
    image: node
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: [sh, -c, "npm install sleep 2 && node index.js"]
    networks:
      appnet:
        ipv4_address: 172.25.0.101

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24